from models.model import Model
from tensorflow.keras import Sequential, layers, models
from tensorflow.keras.layers.experimental.preprocessing import Rescaling
from tensorflow.keras.optimizers import RMSprop, Adam

class RandomModel(Model):
    def _define_model(self, input_shape, categories_count):
        # you have to initialize self.model to a keras model
        # very similar to transfered_model.py, the only difference is that you should randomize the weights
        # load your basic model with keras's load_model function
        # freeze the weights of the loaded model to make sure the training doesn't affect them
        # (check the number of total params, trainable params and non-trainable params in your summary generated by train_transfer.py)
        # randomize the weights of the loaded model, possibly by using _randomize_layers
        # use this model by removing the last layer, adding dense layers and an output layer
        
        base_model = models.load_model('results/basic_model_10_70_percent.keras')
        
        for layer in base_model.layers:
            layer.trainable = False
        
        # Randomize the weights of the loaded model
        self._randomize_layers(base_model)
        
        base_model = models.Model(inputs=base_model.inputs, outputs=base_model.layers[-2].output)
        
    
        x = layers.Flatten(name='random_flatten')(base_model.output)
        x = layers.Dense(64, activation='relu', name='random_dense_1')(x)
        x = layers.Dropout(0.5, name='random_dropout')(x)
        x = layers.Dense(1, activation='sigmoid', name='random_output')(x) 

        self.model = models.Model(inputs=base_model.input, outputs=x)
    
    def _compile_model(self):
        self.model.compile(
            optimizer=RMSprop(learning_rate=0.001),
            loss='binary_crossentropy',
            metrics=['accuracy']
        )

    @staticmethod
    def _randomize_layers(model):
        for layer in model.layers:
            if hasattr(layer, 'kernel_initializer') and layer.kernel is not None:
                layer.kernel.assign(layer.kernel_initializer(layer.kernel.shape))
            if hasattr(layer, 'bias_initializer') and layer.bias is not None:
                layer.bias.assign(layer.bias_initializer(layer.bias.shape))